trigger:
- dev/*

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  packageVersion: '1.0.0'

steps:
- template: pipeline-steps/step_restore_build_pack.yml

- template: pipeline-steps/step_run_all_tests.yml
