trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- template: pipeline-steps/step_install_snk.yml

- template: pipeline-steps/step_restore_build_pack.yml

- template: pipeline-steps/step_run_all_tests.yml

# - task: NuGetCommand@2
#   displayName: "NuGet push local source"
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
#     nuGetFeedType: 'internal'
#     publishVstsFeed: '8f2ada46-a80c-44b6-ab21-45b5fbae5c6d'
    
# - task: NuGetCommand@2
#   displayName: "NuGet push nuget.org"
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'NugetOrg'
