trigger:
- release/*

pool:
  vmImage: 'windows-latest'

variables:
  solutionName: 'ComboPatterns'
  solution: '**/$(solutionName).sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorVersion: '3'
  minorVersion: '0'
  pathVersion: '3'
  packageVersion: '$(majorVersion).$(minorVersion).$(pathVersion)'
  packageFileName: '$(solutionName).$(packageVersion).nupkg'

steps:
- template: pipeline-steps/step_install_snk.yml

- template: pipeline-steps/step_restore_build_pack.yml

- template: pipeline-steps/step_run_all_tests.yml

- template: pipeline-steps/step_copy_nuget_to_artifacts.yml

- task: NuGetCommand@2
  displayName: "NuGet push nuget.org"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/$(solutionName)/$(packageFileName)'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'
